name: Build Windows Version

on:
  push:
    branches: [master-dev]
  workflow_dispatch:

jobs:
  BuildWindows:
    name: Build Windows
    permissions: write-all
    runs-on: windows-2022 # Nutzt einen echten Windows-Server
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            .haxelib
            export/release/windows/obj
          # Neuer Cache-Name gegen alte Fehler
          key: Juto-Windows-Final-V1-${{ hashFiles('setup/*.sh', 'setup/*.bat') }}

      - name: Install Libraries
        # Wir nutzen Bash auf Windows, damit deine unix.sh funktioniert!
        shell: bash
        run: sh ./setup/unix.sh

      - name: Rebuild Lime Tools
        run: haxelib run lime rebuild windows -nohl --quiet

      - name: Build Game
        run: haxelib run lime build windows -final

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Project-Juto-Windows
          path: export/release/windows/bin/*
